# https://github.com/marketplace/actions/auto-merge-pull-request

name: Auto-Merge Pull Request

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2.8.0
        with:
          required-labels: dependencies